#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v24
# autospec commit: a88ffdc
#
Name     : gnome-control-center
Version  : 48.1
Release  : 115
URL      : https://download.gnome.org/sources/gnome-control-center/48/gnome-control-center-48.1.tar.xz
Source0  : https://download.gnome.org/sources/gnome-control-center/48/gnome-control-center-48.1.tar.xz
Summary  : Keybindings configuration for GNOME applications
Group    : Development/Tools
License  : GPL-2.0 MIT
Requires: gnome-control-center-bin = %{version}-%{release}
Requires: gnome-control-center-data = %{version}-%{release}
Requires: gnome-control-center-libexec = %{version}-%{release}
Requires: gnome-control-center-license = %{version}-%{release}
Requires: gnome-control-center-locales = %{version}-%{release}
Requires: glibc-locale
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : colord
BuildRequires : colord-gtk-dev
BuildRequires : cups-dev
BuildRequires : docbook-xml
BuildRequires : e2fsprogs-dev
BuildRequires : glibc-locale
BuildRequires : gsettings-desktop-schemas-dev
BuildRequires : gsound-dev
BuildRequires : intltool
BuildRequires : krb5-dev
BuildRequires : libgtop-dev
BuildRequires : libsoup-dev
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(accountsservice)
BuildRequires : pkgconfig(colord-gtk)
BuildRequires : pkgconfig(gcr-4)
BuildRequires : pkgconfig(gnome-bluetooth-3.0)
BuildRequires : pkgconfig(gnome-desktop-3.0)
BuildRequires : pkgconfig(gnome-settings-daemon)
BuildRequires : pkgconfig(goa-1.0)
BuildRequires : pkgconfig(grilo-0.3)
BuildRequires : pkgconfig(gsound)
BuildRequires : pkgconfig(gudev-1.0)
BuildRequires : pkgconfig(ibus-1.0)
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(libgtop-2.0)
BuildRequires : pkgconfig(libhandy-1)
BuildRequires : pkgconfig(libnm)
BuildRequires : pkgconfig(libnma)
BuildRequires : pkgconfig(libpulse)
BuildRequires : pkgconfig(libsecret-1)
BuildRequires : pkgconfig(libwacom)
BuildRequires : pkgconfig(mm-glib)
BuildRequires : pkgconfig(polkit-gobject-1)
BuildRequires : pkgconfig(pwquality)
BuildRequires : pkgconfig(smbclient)
BuildRequires : pkgconfig(tecla)
BuildRequires : pkgconfig(udisks2)
BuildRequires : pkgconfig(upower-glib)
BuildRequires : setxkbmap
BuildRequires : shared-mime-info
BuildRequires : udisks2-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: Check-country-value.patch

%description
Those translations are copied from system-config-date
http://git.fedorahosted.org/git/?p=system-config-date.git;a=tree;f=po/timezones
and should not be modified by the GNOME translation teams.

%package bin
Summary: bin components for the gnome-control-center package.
Group: Binaries
Requires: gnome-control-center-data = %{version}-%{release}
Requires: gnome-control-center-libexec = %{version}-%{release}
Requires: gnome-control-center-license = %{version}-%{release}

%description bin
bin components for the gnome-control-center package.


%package data
Summary: data components for the gnome-control-center package.
Group: Data

%description data
data components for the gnome-control-center package.


%package dev
Summary: dev components for the gnome-control-center package.
Group: Development
Requires: gnome-control-center-bin = %{version}-%{release}
Requires: gnome-control-center-data = %{version}-%{release}
Provides: gnome-control-center-devel = %{version}-%{release}
Requires: gnome-control-center = %{version}-%{release}

%description dev
dev components for the gnome-control-center package.


%package libexec
Summary: libexec components for the gnome-control-center package.
Group: Default
Requires: gnome-control-center-license = %{version}-%{release}

%description libexec
libexec components for the gnome-control-center package.


%package license
Summary: license components for the gnome-control-center package.
Group: Default

%description license
license components for the gnome-control-center package.


%package locales
Summary: locales components for the gnome-control-center package.
Group: Default

%description locales
locales components for the gnome-control-center package.


%prep
%setup -q -n gnome-control-center-48.1
cd %{_builddir}/gnome-control-center-48.1
%patch -P 1 -p1
pushd ..
cp -a gnome-control-center-48.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1744727161
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
GOAMD64=v3
CFLAGS="$CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/gnome-control-center
cp %{_builddir}/gnome-control-center-%{version}/COPYING %{buildroot}/usr/share/package-licenses/gnome-control-center/13d2034b5ee3cb8d1a076370cf8f0e344a5d0855 || :
cp %{_builddir}/gnome-control-center-%{version}/panels/wacom/calibrator/COPYING %{buildroot}/usr/share/package-licenses/gnome-control-center/5dfd8a387b5dd2491e61f9649b1cec0ab059c0dd || :
GOAMD64=v3
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang gnome-control-center-2.0
%find_lang gnome-control-center-2.0-timezones
## install_append content
mkdir -p %{buildroot}/usr/lib64/pkgconfig
mv %{buildroot}/usr/share/pkgconfig/gnome-keybindings.pc %{buildroot}/usr/lib64/pkgconfig/
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/gnome-control-center
/usr/bin/gnome-control-center

%files data
%defattr(-,root,root,-)
/usr/share/applications/gnome-about-panel.desktop
/usr/share/applications/gnome-applications-panel.desktop
/usr/share/applications/gnome-background-panel.desktop
/usr/share/applications/gnome-bluetooth-panel.desktop
/usr/share/applications/gnome-color-panel.desktop
/usr/share/applications/gnome-datetime-panel.desktop
/usr/share/applications/gnome-display-panel.desktop
/usr/share/applications/gnome-keyboard-panel.desktop
/usr/share/applications/gnome-mouse-panel.desktop
/usr/share/applications/gnome-multitasking-panel.desktop
/usr/share/applications/gnome-network-panel.desktop
/usr/share/applications/gnome-notifications-panel.desktop
/usr/share/applications/gnome-online-accounts-panel.desktop
/usr/share/applications/gnome-power-panel.desktop
/usr/share/applications/gnome-printers-panel.desktop
/usr/share/applications/gnome-privacy-panel.desktop
/usr/share/applications/gnome-region-panel.desktop
/usr/share/applications/gnome-search-panel.desktop
/usr/share/applications/gnome-sharing-panel.desktop
/usr/share/applications/gnome-sound-panel.desktop
/usr/share/applications/gnome-system-panel.desktop
/usr/share/applications/gnome-universal-access-panel.desktop
/usr/share/applications/gnome-users-panel.desktop
/usr/share/applications/gnome-wacom-panel.desktop
/usr/share/applications/gnome-wellbeing-panel.desktop
/usr/share/applications/gnome-wifi-panel.desktop
/usr/share/applications/gnome-wwan-panel.desktop
/usr/share/applications/org.gnome.Settings.desktop
/usr/share/bash-completion/completions/gnome-control-center
/usr/share/dbus-1/interfaces/org.gnome.GlobalShortcutsRebind.xml
/usr/share/dbus-1/services/org.gnome.Settings.GlobalShortcutsProvider.service
/usr/share/dbus-1/services/org.gnome.Settings.SearchProvider.service
/usr/share/dbus-1/services/org.gnome.Settings.service
/usr/share/gettext/its/gnome-keybindings.its
/usr/share/gettext/its/gnome-keybindings.loc
/usr/share/gettext/its/sounds.its
/usr/share/gettext/its/sounds.loc
/usr/share/glib-2.0/schemas/org.gnome.Settings.gschema.xml
/usr/share/gnome-control-center/keybindings/00-multimedia.xml
/usr/share/gnome-control-center/keybindings/01-input-sources.xml
/usr/share/gnome-control-center/keybindings/01-launchers.xml
/usr/share/gnome-control-center/keybindings/01-system.xml
/usr/share/gnome-control-center/keybindings/50-accessibility.xml
/usr/share/gnome-control-center/pixmaps/noise-texture-light.png
/usr/share/gnome-shell/search-providers/org.gnome.Settings.search-provider.ini
/usr/share/icons/gnome-logo-text-dark.svg
/usr/share/icons/gnome-logo-text.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-about-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-accessibility-hearing-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-accessibility-pointing-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-accessibility-seeing-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-accessibility-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-accessibility-typing-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-accessibility-zoom-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-appearance-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-applications-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-bluetooth-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-camera-access-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-color-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-desktop-sharing-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-device-diagnostics-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-device-security-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-display-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-keyboard-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-location-access-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-microphone-access-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-mobile-network-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-mouse-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-multitasking-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-network-proxy-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-network-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-notifications-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-online-accounts-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-power-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-printers-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-privacy-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-region-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-remote-desktop-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-screen-lock-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-screen-time-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-search-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-secure-shell-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-sharing-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-sound-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-system-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-thunderbolt-access-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-time-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-trash-file-history-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-users-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-wacom-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings-wellbeing-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings.Devel.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Settings.svg
/usr/share/icons/hicolor/symbolic/apps/org.gnome.Settings-symbolic.svg
/usr/share/metainfo/org.gnome.Settings.appdata.xml
/usr/share/pixmaps/faces/bicycle.jpg
/usr/share/pixmaps/faces/book.jpg
/usr/share/pixmaps/faces/calculator.jpg
/usr/share/pixmaps/faces/cat.jpg
/usr/share/pixmaps/faces/coffee2.jpg
/usr/share/pixmaps/faces/flower2.jpg
/usr/share/pixmaps/faces/gamepad.jpg
/usr/share/pixmaps/faces/guitar2.jpg
/usr/share/pixmaps/faces/headphones.jpg
/usr/share/pixmaps/faces/hummingbird.jpg
/usr/share/pixmaps/faces/mountain.jpg
/usr/share/pixmaps/faces/plane.jpg
/usr/share/pixmaps/faces/surfer.jpg
/usr/share/pixmaps/faces/tomatoes.jpg
/usr/share/pixmaps/faces/tree.jpg
/usr/share/polkit-1/actions/org.gnome.controlcenter.remote-login-helper.policy
/usr/share/polkit-1/actions/org.gnome.controlcenter.remote-session-helper.policy
/usr/share/polkit-1/actions/org.gnome.controlcenter.system.policy
/usr/share/polkit-1/actions/org.gnome.controlcenter.user-accounts.policy
/usr/share/polkit-1/rules.d/gnome-control-center.rules
/usr/share/sounds/gnome/default/alerts/click.ogg
/usr/share/sounds/gnome/default/alerts/hum.ogg
/usr/share/sounds/gnome/default/alerts/string.ogg
/usr/share/sounds/gnome/default/alerts/swing.ogg

%files dev
%defattr(-,root,root,-)
/usr/lib64/pkgconfig/gnome-keybindings.pc

%files libexec
%defattr(-,root,root,-)
/V3/usr/libexec/gnome-control-center-global-shortcuts-provider
/V3/usr/libexec/gnome-control-center-print-renderer
/V3/usr/libexec/gnome-control-center-search-provider
/usr/libexec/gnome-control-center-global-shortcuts-provider
/usr/libexec/gnome-control-center-print-renderer
/usr/libexec/gnome-control-center-search-provider

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gnome-control-center/13d2034b5ee3cb8d1a076370cf8f0e344a5d0855
/usr/share/package-licenses/gnome-control-center/5dfd8a387b5dd2491e61f9649b1cec0ab059c0dd

%files locales -f gnome-control-center-2.0.lang -f gnome-control-center-2.0-timezones.lang
%defattr(-,root,root,-)

